tasks:
  - name: terraform
    env:
      TF_LOG: DEBUG 
    before: |
      cd $PROJECT_ROOT
      source ./bin/set_tf_alias
      source ./bin/install.terraform.cli
      source ./bin/generate_tfrc_credentials
      cp $PROJECT_ROOT/terraform.tfvars.example $PROJECT_ROOT/terraform.tfvars
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      cd $PROJECT_ROOT
      source ./bin/set_tf_alias
      source ./bin/install_aws_cli
  - name: http-server
    before: |
      cd $PROJECT_ROOT
      npm install --global http-server
    command:
      http-server
  - name: sinatra
    before: | 
      cd terratowns_mock_server
      bundle install
      bundle exec ruby server.rb 
vscode:
  extensions:
    - amazonwebservices.aws-toolkit-vscode
    - hashicorp.terraform
    - mhutchie.git-graph
    - phil294.git-log--graph
    - eamodio.gitlens
    - furkanozalp.go-syntax

